### ISSUE TITLE
flask create-db fail

### ISSUE THREAD

**Issue by mhanuel26** [enwawerueli/flask-skeleton#2]
Hi, 

I follow the exact steps to configure and this command fails, and when using the example web app, after any login related command I got a problem with the alchemy database, like some missing tables.

`$ flask create-db
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'create-db'.
`

What could be wrong?

Thanks,

**Comment by mhanuel26** [comment]
Ohh it seems I miss the following, perhaps you can add to the instructions

export FLASK_APP=wsgi.py

Thanks

**Comment by enwawerueli** [comment]
If you created the virtual environment yourself, make sure to install `python-dotenv` package which autoloads this environment variable, (this should already be installed if you used the `--env` option with `create-flask-app` to create the virtual environment). Otherwise, you have to set it yourself like you did.
